
version: '3'
volumes:
  mongo-keys:

services:
  mongo-keys:
    image: depop/openssl-bats
    volumes:
      - mongo-keys:/mongo-conf
    command: 'bash -c "openssl rand -base64 741 > /mongo-conf/mongodb-keyfile; chmod 600 /mongo-conf/mongodb-keyfile; chown 999 /mongo-conf/mongodb-keyfile"'

  mongodb:
    container_name: mongodb
    hostname: mongodb
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo-keys:/opt/keyfile
      - ./data:/data/db
    command: 'mongod --auth --keyFile /opt/keyfile/mongodb-keyfile  --replSet rs0'
    depends_on:
        - mongo-keys
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123123
      - MONGO_INITDB_DATABASE=TestDBD8
      - MONGO_REPLICA_SET_NAME=rs0
    networks:
      - mongo-network

  mongodb-secondary1:
    container_name: mongodb-secondary1
    hostname: mongodb-secondary1
    image: mongo:latest
    restart: always
    ports:
      - 27018:27017
    depends_on:
      - mongo-keys
    volumes:
      - mongo-keys:/opt/keyfile
      - ./data/secondary1:/data/db
    command: 'mongod --auth --keyFile /opt/keyfile/mongodb-keyfile --replSet rs0'
    depends_on:
        - mongo-keys
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123123
      - MONGO_REPLICA_SET_NAME=rs0
      - MONGO_PRIMARY_HOST=mongodb
      - MONGO_PRIMARY_PORT=27017
    networks:
      - mongo-network

  init-replica-set:
    image: mongo:latest
    depends_on:
      - mongodb
      - mongodb-secondary1
    command: >
      mongosh --host 111.111.111.11:27017 -u root -p 123123 --eval 
      '
      config = {
      "_id" : "rs0",
      "members" : [
        {
          "_id" : 0,
          "host" : "111.111.111.11:27017",
          "priority":2
        },
        {
          "_id" : 1,
          "host" : "111.111.111.11:27018"
        }
      ]
      };
      rs.initiate(config);
      '   
    networks:
      - mongo-network


networks:  
  mongo-network:
